### ISSUE TITLE
How is Uruguay "the south­most country of South America"?

### ISSUE THREAD

**Issue by lolmaus** [mvdwg/mvdwg.github.io#20]
> Uruguay — the south­most country of South America! 

This statement sounds false...

**Comment by marpo60** [comment]
Hi! Its a controversial statement but we are referring to this:

![image](https://user-images.githubusercontent.com/952074/28675696-f78cffde-72be-11e7-8b4e-effec21a93de.png)

We don't think its a false statement its a matter of perspective.
Glad that you know where Uruguay is!!! Most people don't have a clue :(

Maybe we could change it to the southernmost capital city of south america :)

**Comment by lolmaus** [comment]
So your concept of "the southernmost country" is not a country whose southernmost point is closer to the south, but rather a country whose **northernmost** point is closer to the south?

Reminded me of Randy explaining why his dick should be considered large, even though its length is small:

![Randy's system](http://i.imgur.com/Q9wACho.gif)

Please don't get me wrong. I respect Uruguay and I dream of visiting Montevideo one day, but the statement "Uruguay is the south­ernmost country of South America" is plain false.

You could use "one of southern­most countries of the whole world" instead.

**Comment by san650** [comment]
@lolmaus thanks for the feedback. We'll update the copy.

**Comment by san650** [comment]
Changed.

![screen shot 2017-07-27 at 11 59 25 am](https://user-images.githubusercontent.com/1234607/28677198-249498e4-72c3-11e7-9794-ca0fb70d9a43.png)
